packages:
  - apps/*
  - packages/*
catalog:
  eslint: ^9.36.0
  typescript: ^5.9.2
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js-pure
  - esbuild
  - sharp
