packages:
  - apps/*
  - packages/*
catalog:
  eslint: ^9.30.1
  typescript: ^5.8.3
onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vercel/speed-insights'
  - core-js-pure
  - esbuild
  - sharp
