// Generated by Wrangler by running `wrangler types`

interface Env {
	COURSE_REGISTRY_URL: "https://uocampus.public.uottawa.ca/psc/csprpr9pub/EMPLOYEE/SA/c/UO_SR_AA_MODS.UO_PUB_CLSSRCH.GBL";
	COURSE_CATALOGUE_URL: "https://catalogue.uottawa.ca/en/courses/";
	HYPERDRIVE: Hyperdrive;
	MAIN_WORKFLOW: Workflow;
	TERMS_WORKFLOW: Workflow;
	SUBJECTS_WORKFLOW: Workflow;
}
