import type { PostgresJsDatabase } from "drizzle-orm/postgres-js";
import { courseComponentsTable } from "../schema.js";

const courseComponents = [
  {
    courseCode: "ADM1100",
    term: "2255",
    section: "X00",
    subSection: "X00",
    isOpen: false,
    type: "LEC",
  },
  {
    courseCode: "ADM1100",
    term: "2259",
    section: "A00",
    subSection: "A00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "ADM1100",
    term: "2259",
    section: "B00",
    subSection: "B00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "ADM1100",
    term: "2261",
    section: "M00",
    subSection: "M00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "ITI1100",
    term: "2255",
    section: "Z00",
    subSection: "Z00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "ITI1100",
    term: "2255",
    section: "Z00",
    subSection: "Z01",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2255",
    section: "Z00",
    subSection: "Z02",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2255",
    section: "Z00",
    subSection: "Z03",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2255",
    section: "Z00",
    subSection: "Z04",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A07",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B01",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B02",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B03",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A06",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B04",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B05",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B06",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "B00",
    subSection: "B07",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "C00",
    subSection: "C00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "C00",
    subSection: "C01",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "C00",
    subSection: "C02",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "C00",
    subSection: "C03",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "C00",
    subSection: "C04",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "C00",
    subSection: "C05",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "C00",
    subSection: "C06",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A01",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A02",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A03",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A04",
    isOpen: true,
    type: "LAB",
  },
  {
    courseCode: "ITI1100",
    term: "2261",
    section: "A00",
    subSection: "A05",
    isOpen: true,
    type: "TUT",
  },
  {
    courseCode: "MAT1320",
    term: "2255",
    section: "X00",
    subSection: "X00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "MAT1320",
    term: "2255",
    section: "X00",
    subSection: "X01",
    isOpen: false,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2255",
    section: "X00",
    subSection: "X02",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2255",
    section: "X00",
    subSection: "X03",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "C00",
    subSection: "C03",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "C00",
    subSection: "C04",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "E00",
    subSection: "E00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "MAT1320",
    term: "2261",
    section: "D00",
    subSection: "D00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "MAT1320",
    term: "2261",
    section: "D00",
    subSection: "D01",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2261",
    section: "D00",
    subSection: "D02",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2261",
    section: "D00",
    subSection: "D03",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2261",
    section: "D00",
    subSection: "D04",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "A00",
    subSection: "A00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "E00",
    subSection: "E01",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "E00",
    subSection: "E02",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "E00",
    subSection: "E03",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "E00",
    subSection: "E04",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "H00",
    subSection: "H00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "H00",
    subSection: "H01",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "H00",
    subSection: "H02",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "H00",
    subSection: "H03",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "A00",
    subSection: "A01",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "A00",
    subSection: "A02",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "A00",
    subSection: "A03",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "A00",
    subSection: "A04",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "A00",
    subSection: "A05",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "B00",
    subSection: "B00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "B00",
    subSection: "B01",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "B00",
    subSection: "B02",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "B00",
    subSection: "B03",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "B00",
    subSection: "B04",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "C00",
    subSection: "C00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "C00",
    subSection: "C01",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "MAT1320",
    term: "2259",
    section: "C00",
    subSection: "C02",
    isOpen: true,
    type: "DGD",
  },
  {
    courseCode: "CLA1101",
    term: "2255",
    section: "A00",
    subSection: "A00",
    isOpen: true,
    type: "LEC",
  },
  {
    courseCode: "CLA1101",
    term: "2259",
    section: "B00",
    subSection: "B00",
    isOpen: true,
    type: "LEC",
  },
];

export async function seedCourseComponents(db: PostgresJsDatabase) {
  await db.insert(courseComponentsTable).values(courseComponents);
  console.log("Seeded database with course components.");
}
